[package]
name = "dump_syms"
version = "0.0.1"
authors = ["Calixte Denizet <cdenizet@mozilla.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
clap = "2.33"
failure = "0.1"
fxhash = "0.2"
is_sorted = "0.1"
log = "0.4"
pdb = { git = "https://github.com/willglynn/pdb", rev = "64757397c4aea7fcb4f045b89c05c25d7a84b42e"}
simplelog = "0.7"
symbolic-common = { git = "https://github.com/getsentry/symbolic/", rev = "723fb7f558d722f344ba4d847db1052974346f31" }
symbolic-debuginfo = { git = "https://github.com/getsentry/symbolic/", rev = "723fb7f558d722f344ba4d847db1052974346f31" }
symbolic-demangle = { git = "https://github.com/getsentry/symbolic/", rev = "723fb7f558d722f344ba4d847db1052974346f31" }
symbolic-minidump = { git = "https://github.com/getsentry/symbolic/", rev = "723fb7f558d722f344ba4d847db1052974346f31" }
uuid = "0.7"
