[package]
name = "dump_syms"
version = "0.0.5"
authors = ["Calixte Denizet <cdenizet@mozilla.com>"]
repository = "https://github.com/mozilla/dump_syms"
homepage = "https://github.com/mozilla/dump_syms"
description = "Dump debug symbols into Breakpad ones"
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "1.2"
cab = "0.2"
clap = "2.33"
dirs = "2.0"
failure = "0.1"
futures = "0.3"
hashbrown = "0.7"
log = "0.4"
pdb = "0.6"
reqwest = { version = "0.10", features = ["blocking"] }
simplelog = "0.8"
symbolic-common = "7.3"
symbolic-debuginfo = "7.3"
symbolic-demangle = "7.3"
symbolic-minidump = "7.3"
tokio = "0.2"
url = "2.1"
uuid = "0.8"

[dev-dependencies]
fxhash = "0.2"
tempfile = "3"

[features]
vendored-openssl = ["openssl/vendored"]

[dependencies.openssl]
version = "0.10"
optional = true

[patch.crates-io]

[profile.release]
lto = true
