[package]
name = "dump_syms"
version = "0.0.7"
authors = ["Calixte Denizet <cdenizet@mozilla.com>"]
repository = "https://github.com/mozilla/dump_syms"
homepage = "https://github.com/mozilla/dump_syms"
description = "Dump debug symbols into Breakpad ones"
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "1.3"
cab = "0.2"
clap = "3.1"
crossbeam = "0.8.1"
dirs = "3.0"
failure = "0.1"
futures = "0.3"
goblin = "0.5.1" # Keep in sync with symbolic-debuginfo
hashbrown = { version = "0.11", features = ["serde"] }
lazy_static = "1.4"
log = "0.4"
num_cpus = "1.13"
pdb = "0.7"
regex = "1.4"
reqwest = { version = "0.11", features = ["blocking"] }
serde = "1.0"
serde_json = "1.0"
sha2 = "0.9"
simplelog = "0.10"
symbolic = { version = "8", features = ["demangle", "minidump"] }
tokio = "1.8"
url = "2.2"
uuid = "0.8"

[dev-dependencies]
fxhash = "0.2"
tempfile = "3"

[features]
vendored-openssl = ["openssl/vendored"]

[dependencies.openssl]
version = "0.10"
optional = true
