[package]
name = "dump_syms"
version = "0.0.1"
authors = ["Calixte Denizet <cdenizet@mozilla.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
clap = "2.33.0"
goblin = "0.0.23"
is_sorted = "0.1.1"
log = "0.4.8"
pdb = { git = "https://github.com/willglynn/pdb", rev = "2ebb389828b349a28cf42e83c9ba5bf7bbfda6ed"}
simplelog = "0.7.3"
symbolic-common = "6.1.4"
symbolic-debuginfo = "6.1.4"
symbolic-demangle = "6.1.4"
symbolic-minidump = "6.1.4"
uuid = "0.7.2"
